env:
  global:
    - PGUSER=postgres
    - RUNTESTFLAGS=-v
before_install:
  #- rm .travis.yml
  - sudo apt-get update
  #- apt-cache search libgdal
  - sudo apt-get purge -q postgresql-9.3 postgresql-9.2 postgresql-9.1-postgis-scripts postgresql-9.2-postgis-scripts postgresql-9.3-postgis-scripts postgresql-client postgresql-client-9.2  postgresql-client-9.3 liblwgeom-2.1.3 postgis
  - sudo apt-get autoremove -q --purge
  - sudo apt-get install -q build-essential flex autoconf libtool gfortran postgresql-server-dev-9.1 postgresql-client-9.1 postgresql-9.1 xsltproc libjson0-dev libproj-dev dblatex xsltproc libcunit1-dev libcunit1 docbook-xsl docbook-mathml libgdal-dev libgeos-dev
  - dpkg -l | grep postgresql
  - git config --global user.name "PostGIS Travis CI"
  - git config --global user.email $HOSTNAME":not-for-mail@travis-ci.org"
  - ./autogen.sh
language: c
compiler:
  - gcc
notifications:
  email: false
  irc:
    channels:
      - "irc.freenode.org#postgis"
    on_success: change
    on_failure: always
    use_notice: false
#after_failure:
#  - cat /tmp/pgis_reg/*
